---
- name: Create Multiple Workload Definitions
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/auth.yaml
    - vars/basics.yaml
    - vars/definitions.yaml
    - vars/deployments.yaml

  module_defaults:
    cisco.intersight.intersight_rest_api:
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri }}"
      validate_certs: "{{ validate_certs }}"

  vars:
    unified_edge:
      Name: UnifiedEdgeChassis
      Blueprint:
        Moid: 68dc8a036e75733101ab7068
        ObjectType: workload.Blueprint
      Input:
        ImcAccessConfiguration:
          IpAddressPool:
            Moid: "{{ ip_pool.api_response.Moid }}"
            ObjectType: ippool.Pool
          VlanId: "{{ mgmt_vlan }}"
        SwitchFirmwareVersion: "{{ chassis_firmware }}"
        LocalUsers:
          SourceMoid: "{{ local_user.api_response.EndPointUserPolicy.Moid }}"
          ObjectType: iam.EndPointUserPolicy
        Password: "{{ password }}"
        Timezone: "{{ timezone }}"
        Dns:
          IpVersion: Ipv4
          PrimaryDnsServer: "{{ dns_servers[0] }}"
          SecondaryDnsServer: "{{ dns_servers[1] }}"
        SwitchConfiguration:
          MacAgingSettings:
            MacAgingOption: Default
          EnableJumboFrame: "{{ jumbo_frames }}"
        PortConfiguration:
          UplinkPorts: "{{ uplink_ports }}"
          UnifiedEdgePortSpeed: Auto
        VlanConfiguration:
          Vlans: "{{ allowed_vlans }}"
        NtpConfiguration:
          NtpServers: "{{ ntp_servers }}"
        SerialOverLanPolicy:
          SolEnabled: false
        PowerConfiguration:
          RedundancyMode: Grid
        ThermalConfiguration:
          FanControlMode: Balanced
        SyslogConfiguration:
          SyslogServers:
          - Enabled: false
      InputOverride:
      - Timezone
      - NtpConfiguration
      - Dns
      ResourceConstraint:
        Input:
          DeviceModel: UCSXE-ECMC-G1

    ubuntu_server:
      Name: Ubuntu Server
      Blueprint:
        Moid: 68dc8a046e75733101ab709e
        ObjectType: workload.Blueprint
      Input:
        ServerFirmwareVersion: "{{ server_firmware }}"
        ServerVlanSettings:
          VlanList: "{{ os_vlans }}"
        OsDetails:
          Version: Ubuntu Server 24.04.3 LTS
          Hostname: ubuntu
          DeriveHostname: false
          Password: "{{ password }}"
          Vendor:
            Moid: 5b7370f16836726e35cc7024
            ObjectType: hcl.OperatingSystemVendor
          OsImage:
            Moid: "{{ ubuntu_image }}"
            ObjectType: softwarerepository.OperatingSystemFile
          ScuImage:
            Moid: "{{ scu_image }}"
            ObjectType: firmware.ServerConfigurationUtilityDistributable
        OsNetworkConfig:
          IpConfigType: DHCP
          DhcpVersionType: IPv4
      InputOverride: []
      ResourceConstraint:
        Input:
          SlotId: 1

  tasks:
  - name: Get Base Organization
    cisco.intersight.intersight_rest_api:
      resource_path: /organization/Organizations
      query_params:
        $filter: "Name eq '{{ base_org }}'"
    register: base_org_result

  - name: Local User Policy
    cisco.intersight.intersight_local_user_policy:
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri }}"
      validate_certs: "{{ validate_certs }}"
      name: "{{ base_name }}"
      description: "Local User Policy for Fleet Management"
      organization: "{{ base_org }}"
      local_users: "{{ local_users }}"
      state: present
    register: local_user

  - name: Debug Local User Policy Response
    debug:
      msg: "ObjectType: {{ local_user.api_response.ObjectType }}, Moid: {{ local_user.api_response.Moid }}"

  - name: IP Pool
    cisco.intersight.intersight_ip_pool:
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri }}"
      validate_certs: "{{ validate_certs }}"
      name: "{{ base_name }}"
      description: "IP Pool for Fleet Management"
      organization: "{{ base_org }}"
      ipv4_config:
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        primary_dns: "{{ dns_servers[0] }}"
        secondary_dns: "{{ dns_servers[1] }}"
      ipv4_blocks: "{{ ip_range }}"
      state: present
    register: ip_pool

  - name: Build Blueprint Arrays - Add Chassis
    set_fact:
      blueprints_by_definition: "{{ blueprints_by_definition | default({}) | combine({ item.name: [unified_edge | combine({'RefName': unified_edge.Name | replace(' - ', '___') | replace(' ', '_')}, recursive=True) | combine(item.chassis_overrides | default({}), recursive=True)] }) }}"
    loop: "{{ definitions }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Build Blueprint Arrays - Add Servers
    set_fact:
      blueprints_by_definition: >-
        {{
          blueprints_by_definition | combine({
            item.0.name:
              blueprints_by_definition[item.0.name] + [
                ubuntu_server | combine({
                  'Name': 'Ubuntu Server - Slot ' ~ item.1.slot_id,
                  'RefName': ('Ubuntu Server - Slot ' ~ item.1.slot_id) | replace(' - ', '___') | replace(' ', '_'),
                  'Input': ubuntu_server.Input | combine({
                    'OsDetails': ubuntu_server.Input.OsDetails | combine({
                      'Hostname': 'ubuntu' ~ item.1.slot_id
                    })
                  }, recursive=True)
                }, recursive=True) | combine(item.1.overrides | default({}), recursive=True) | combine({
                  'ResourceConstraint': {
                    'Input': {
                      'SlotId': item.1.slot_id
                    }
                  }
                }, recursive=True)
              ]
          })
        }}
    loop: "{{ definitions | subelements('blueprints') }}"
    loop_control:
      label: "{{ item.0.name }} - Slot {{ item.1.slot_id }}"

  - name: Query Existing Workload Definitions
    cisco.intersight.intersight_rest_api:
      resource_path: /workload/WorkloadDefinitions
      query_params:
        $filter: "Name eq '{{ base_name }} {{ item.name }}'"
        $orderby: "Version desc"
        $top: 1
    register: existing_definitions
    loop: "{{ definitions }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Set Version Numbers
    set_fact:
      existing_versions: >-
        {{
          existing_versions | default({}) | combine({
            item.item.name: (
              (item.api_response.Results[0].Version | int)
              if (item.api_response.Results is defined and item.api_response.Results | length > 0)
              else (item.api_response.Version | int)
              if (item.api_response.Version is defined)
              else 0
            )
          })
        }}
    loop: "{{ existing_definitions.results }}"
    loop_control:
      label: "{{ item.item.name }}"

  - name: Workload Definition - Create New
    cisco.intersight.intersight_rest_api:
      resource_path: /workload/WorkloadDefinitions
      api_body:
        Name: "{{ base_name }} {{ item.name }}"
        Version: 1
        Description: "{{ item.name }} Definition for {{ base_name }}"
        Organization:
          Moid: "{{ base_org_result.api_response.Moid }}"
        PlatformType:
        - UnifiedEdge
        PreferredVersion: true
        Blueprints: "{{ blueprints_by_definition[item.name] }}"
      state: present
    when: existing_versions[item.name] | int == 0
    register: workload_definition_new
    loop: "{{ definitions }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Workload Definition - Update Existing
    cisco.intersight.intersight_rest_api:
      resource_path: /workload/WorkloadDefinitions
      query_params:
        $filter: "Name eq '{{ base_name }} {{ item.name }}' and Version eq {{ existing_versions[item.name] }}"
      api_body:
        Name: "{{ base_name }} {{ item.name }}"
        Version: "{{ existing_versions[item.name] }}"
        Description: "{{ item.name }} Definition for {{ base_name }}"
        Organization:
          Moid: "{{ base_org_result.api_response.Moid }}"
        PlatformType:
        - UnifiedEdge
        PreferredVersion: true
        Blueprints: "{{ blueprints_by_definition[item.name] }}"
      state: present
    when: existing_versions[item.name] | int > 0
    register: workload_definition_update
    failed_when: false
    loop: "{{ definitions }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Workload Definition - New Version
    cisco.intersight.intersight_rest_api:
      resource_path: /workload/WorkloadDefinitions
      query_params:
        $filter: "Name eq '{{ base_name }} {{ item.item.name }}' and Version eq {{ existing_versions[item.item.name] | int + 1 }}"
      api_body:
        Name: "{{ base_name }} {{ item.item.name }}"
        Version: "{{ existing_versions[item.item.name] | int + 1 }}"
        Description: "{{ item.item.name }} Definition for {{ base_name }}"
        Organization:
          Moid: "{{ base_org_result.api_response.Moid }}"
        PlatformType:
        - UnifiedEdge
        PreferredVersion: true
        Blueprints: "{{ blueprints_by_definition[item.item.name] }}"
      state: present
    loop: "{{ workload_definition_update.results }}"
    when: item.failed | default(false)
    loop_control:
      label: "{{ item.item.name }}"

  - name: Build Chassis Serial List
    set_fact:
      all_chassis_serials: >-
        {{
          organizations
          | selectattr('chassis', 'defined')
          | map(attribute='chassis')
          | flatten
          | unique
          | list
        }}
    when: organizations | selectattr('chassis', 'defined') | list | length > 0

  - name: Query All Chassis for Device Registration Moids
    cisco.intersight.intersight_rest_api:
      resource_path: /equipment/Chasses
      return_list: true
      query_params:
        $filter: "Serial in ('{{ all_chassis_serials | join(\"','\") }}')"
        $top: 1000
    register: chassis_query
    when: all_chassis_serials is defined and all_chassis_serials | length > 0

  - name: Build Device Registration Moid Map
    set_fact:
      device_moids_by_org: >-
        {{
          device_moids_by_org | default({}) | combine({
            item.name: (
              chassis_query.api_response
              | selectattr('Serial', 'in', item.chassis)
              | map(attribute='RegisteredDevice.Moid')
              | list
            )
          })
        }}
    loop: "{{ organizations }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - chassis_query is not skipped
      - chassis_query.api_response is defined
      - chassis_query.api_response is iterable
      - item.chassis is defined

  - name: Consumer Resource Groups
    cisco.intersight.intersight_rest_api:
      resource_path: /resource/Groups
      query_params:
        $filter: "Name eq '{{ base_name }}_{{ iter.name }}'"
      api_body:
        Name: "{{ base_name }}_{{ iter.name }}"
        Qualifier: Allow-Selectors
        Selectors: >-
          {{
            [{'Selector': "/api/v1/asset/DeviceRegistrations?$filter=Moid in ('" + "','".join(device_moids_by_org[iter.name]) + "')"}]
            if (device_moids_by_org is defined and iter.name in device_moids_by_org)
            else []
          }}
      state: present
    loop: "{{ organizations }}"
    loop_control:
      loop_var: iter
      label: "{{ base_name }}_{{ iter.name }}"
    register: consumer_rg

  - name: Consumer Organizations
    cisco.intersight.intersight_rest_api:
      resource_path: /organization/Organizations
      query_params:
        $filter: "Name eq '{{ base_name }}_{{ iter.name }}'"
      api_body:
        Name: "{{ base_name }}_{{ iter.name }}"
        Description: "Consumer Organization for Fleet Management in {{ iter.name }}"
        ResourceGroups:
          - "{{ (consumer_rg.results | selectattr('iter.name', 'equalto', iter.name) | first).api_response.Moid }}"
      state: present
    loop: "{{ organizations }}"
    loop_control:
      loop_var: iter
      label: "{{ base_name }}_{{ iter.name }}"
    register: consumer_org

  - name: Organization Sharing
    cisco.intersight.intersight_rest_api:
      resource_path: /iam/SharingRules
      query_params:
        $filter: "Tags/any(t:t/Key eq '{{base_name}}_identifier' and t/Value eq '{{ base_name }}_{{ iter.name }}')"
      api_body:
        ClassId: iam.SharingRule
        ObjectType: iam.SharingRule
        SharedResource:
          ClassId: mo.MoRef
          Moid: "{{ base_org_result.api_response.Moid }}"
          ObjectType: organization.Organization
        SharedWithResource:
          ClassId: mo.MoRef
          Moid: "{{ (consumer_org.results | selectattr('iter.name', 'equalto', iter.name) | first).api_response.Moid }}"
          ObjectType: organization.Organization
        Tags:
          - Key: "{{ base_name }}_identifier"
            Value: "{{ base_name }}_{{ iter.name }}"
            SysTag: false
            Type: "KeyValue"
      state: present
    loop: "{{ organizations }}"
    loop_control:
      loop_var: iter
      label: "{{ base_name }}_{{ iter.name }}"
    register: sharing_rule

  - name: Schedule Policy
    cisco.intersight.intersight_rest_api:
      resource_path: /scheduler/SchedulePolicies
      query_params:
        $filter: "Name eq '{{ base_name }}_{{ iter.org }}'"
      api_body:
        Name: "{{ base_name }}_{{ iter.org }}"
        Description: "Schedule Policy for {{ iter.name }}"
        Organization:
          Moid: >-
            {{
              (base_org_result.api_response.Moid if (base_name + '_Base') == (base_name + '_' + iter.org)
              else (consumer_org.results | selectattr('iter.name', 'equalto', iter.org) | first).api_response.Moid)
            }}
        ScheduleParams: "{{ iter.schedules }}"
        EnableBlockDates: "{{ iter.enable_blocked_dates }}"
        BlockDates: "{{ iter.block_dates }}"
      state: present
    loop: "{{ maintenance }}"
    loop_control:
      loop_var: iter
      label: "{{ base_name }}_{{ iter.org }}"
    register: schedule_policy

  - name: Flatten deployment groups into individual deployments
    set_fact:
      flattened_deployments: >-
        {{
          flattened_deployments | default([]) + [{
            'group_name': item.0.name,
            'group_abbr': item.0.abbr | default(item.0.name[:8]),
            'org': item.0.org,
            'maintenance': item.0.maintenance,
            'timezone': item.0.timezone | default(''),
            'dns_servers': item.0.dns_servers | default([]),
            'ntp_servers': item.0.ntp_servers | default([]),
            'definition': item.1.definition,
            'def_abbr': item.1.abbr | default(item.1.definition[:3]),
            'version': item.1.version | default(item.0.version | default('preferred')),
            'qualifiers': ([{
              'ClassId': 'resource.OdataRuleSetQualifier',
              'ObjectType': 'resource.OdataRuleSetQualifier',
              'Rules': [{
                'ClassId': 'resource.Selector',
                'ObjectType': 'resource.Selector',
                'Selector': item.1.qualifiers
              }]
            }] if (item.1.qualifiers is defined and item.1.qualifiers is not none and item.1.qualifiers | string | length > 0) else []),
            'blueprint_overrides': item.1.blueprint_overrides | default(item.0.blueprint_overrides | default([]))
          }]
        }}
    loop: "{{ deployment_groups | subelements('deployments') }}"
    loop_control:
      label: "{{ item.0.name }} - {{ item.1.definition }}"

  - name: Workload Deployments
    cisco.intersight.intersight_rest_api:
      resource_path: /workload/WorkloadDeployments
      query_params:
        $filter: "Name eq '{{ base_name }}_{{ iter.group_name }}_{{ iter.definition }}'"
      api_body:
        Name: "{{ base_name }}_{{ iter.group_name }}_{{ iter.definition }}"
        Description: 'Workload Deployment for {{ iter.definition }} in {{ iter.group_name }}'
        DigitCount: 2
        Organization:
          Moid: >-
            {{
              base_org_result.api_response.Moid if iter.org == 'Base'
              else (consumer_org.results | selectattr('iter.name', 'equalto', iter.org) | first).api_response.Moid
            }}
        Qualifiers: "{{ iter.qualifiers }}"
        RolloutStrategy:
          BatchSize: 100
          FailureThreshold: 10
          ObjectType: workload.BatchDeployment
        SchedulePolicy:
          Moid: "{{ (schedule_policy.results | selectattr('iter.org', 'equalto', iter.org) | first).api_response.Moid }}"
        StartIndexForSuffix: 1
        WorkloadDefinitionReference: >-
          {{
            {
              'DefinitionName': base_name ~ ' ' ~ iter.definition,
              'Organization': {
                'Moid': base_org_result.api_response.Moid
              },
              'UsePreferredVersion': (iter.version == 'preferred')
            } | combine(
              {'Version': iter.version | int} if iter.version != 'preferred' else {}
            )
          }}
        Blueprints: "{{ iter.blueprint_overrides }}"
        WorkloadInstancePrefix: "{{ base_name }}_{{ iter.group_abbr }}_{{ iter.def_abbr }}"
      state: present
    loop: "{{ flattened_deployments }}"
    loop_control:
      loop_var: iter
      label: "{{ base_name }}_{{ iter.group_name }}_{{ iter.definition }}"
    register: workload_deployment

  - name: Display Results
    debug:
      msg: "Processed {{ definitions | length }} Workload Definitions and {{ organizations | length }} Consumer Organizations: {{ definitions | map(attribute='name') | map('regex_replace', '^(.*)$', base_name + ' \\1') | list }}"
